# Generated by Django 3.2.9 on 2021-12-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=254)),
                ('post_title', models.CharField(blank=True, max_length=80, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('body_text', models.TextField()),
            ],
        ),
    ]
