# Generated by Django 3.2.9 on 2021-12-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
