# Generated by Django 3.2.9 on 2021-12-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211216_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='STRIPE_PRICE_ID',
            new_name='stripe_subscription_price',
        ),
    ]
