# Generated by Django 3.2.9 on 2021-12-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_stripe_price_id_product_stripe_subscription_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=254)),
                ('rating', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('review_text', models.TextField()),
            ],
        ),
    ]
