# Generated by Django 3.2.9 on 2021-12-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_for_product_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=254),
        ),
    ]
