# Generated by Django 3.2.9 on 2021-12-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211216_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_subscription_price',
        ),
    ]
